---
title: "Prep France Data"
format: html
editor: visual
---

```{r}
library(here)
library(tidyverse)
```

```{r}
path <- here("data", "france_2005-22.csv") 
fra_over_2005 <- read.csv(path, header = TRUE, sep = ";")
path <- here("data", "fra_under_2005.csv") 
fra_under_2005 <- read.csv(path, header = TRUE, sep = ",")
```

```{r}
head(fra_over_2005)
head(fra_under_2005)
```

```{r}
fra_over_2005_clean <- fra_over_2005 |>
  mutate(Lexis = if_else(age_atteint == age_revolu, "TL", "TU")) |>
  rename(Year = adec, Sex = sexe, Age = age_revolu, Deaths = nbdec)
```

Saving TU deaths for 2005 for use with 2004 deaths when merging

```{r}
tu_deaths_2005 <- fra_over_2005_clean |>
  filter(Age >= 79, Year == 2005, Lexis == "TU") |>
  mutate(Sex = case_when(
    Sex == 1 ~ "m",
    Sex == 2 ~ "f"
  )) |>
  mutate(Cohort = (Year - Age)) 
```

```{r}
# get TL_Deaths, TU_Deaths_Next_Year and cohort columns
fra_over_2005_clean <- fra_over_2005_clean |>
  arrange(Age, Sex, Year, Lexis) |>
  group_by(Age, Sex) |>
  mutate(TL_Deaths = if_else(Lexis == "TL", Deaths, NA_real_)) |>
  mutate(TU_Deaths_Next_Year = if_else(Lexis == "TU" & 
                                          (lead(Year, 2) == Year + 1), 
                                         lead(Deaths, 2), NA_real_)) |>
  mutate(TU_Deaths_Next_Year = lead(TU_Deaths_Next_Year)) |>
  mutate(Cohort_Deaths = TL_Deaths + TU_Deaths_Next_Year) |>
  ungroup()
  
```

```{r}
fra_over_2005_clean <- fra_over_2005_clean |>
  filter(Lexis == "TL") |>
  select(-Lexis, -age_atteint, -Deaths) |>
  mutate(Sex = case_when(
    Sex == 1 ~ "m",
    Sex == 2 ~ "f"
  )) |>
  mutate(Cohort = (Year - Age)) 
```

```{r}
# prep under 2005 data 
fra_under_2005_clean <- fra_under_2005 |>
  select(-AgeInterval, -country)
```

```{r}
head(fra_under_2005_clean)
head(fra_over_2005_clean)
```

```{r}
merged <- bind_rows(fra_under_2005_clean, fra_over_2005_clean)
```

```{r}
tu_deaths_2005 <- tu_deaths_2005 |>
  arrange(Sex, Age)

tu_deaths_2005_selected <- tu_deaths_2005 |>
  select(Sex, Age, Deaths) |>
  rename(TU_Deaths_Next_Year_2004 = Deaths)

merged_cleaned <- merged |>
  filter(Age >= 79) |>
  arrange(Year, Sex, Age) |>
  left_join(tu_deaths_2005_selected, by = c("Sex", "Age")) |>
  mutate(TU_Deaths_Next_Year = if_else(Year == 2004, TU_Deaths_Next_Year_2004, TU_Deaths_Next_Year)) |>
  mutate(TU_Deaths_Next_Year = if_else(is.na(TU_Deaths_Next_Year), 0, TU_Deaths_Next_Year)) |>
  mutate(Cohort_Deaths = TU_Deaths_Next_Year + TL_Deaths) |>
  select(-TU_Deaths_Next_Year_2004) # Remove the temporary column
```

Extinct Cohort Method

```{r}
# get population counts by summing all future deaths for the cohort 
merged_pop <- merged_cleaned |>
  filter(!is.na(Cohort_Deaths)) |>
  group_by(Cohort, Sex) |>
  arrange(Cohort, Age) |>
  mutate(Population = purrr::map_dbl(Age, ~ sum(Cohort_Deaths[Age >= .x]))) |>
  ungroup()

check_accuracy <- merged_pop |>
  filter(Cohort == 1880, Sex == "f")
```

```{r}
merged_prev_year <- merged_pop |>
  group_by(Sex)|>
  arrange(Age, Year) |>
  mutate(TL_Deaths_Prev_Year = lag(TL_Deaths)) |>
  mutate(TU_Deaths_Same_Year = lag(TU_Deaths_Next_Year)) |>
  ungroup()
```

```{r}
# calculate person-years-lived from population 
merged_exp <- merged_prev_year |>
  group_by(Cohort, Sex) |>
  mutate(Exposure = pmax(0, Population + 1/3*(TL_Deaths_Prev_Year - TU_Deaths_Same_Year))) |>
  mutate(Exposure = if_else(Population == 0 | is.na(Exposure), 0, Exposure)) |>
  ungroup() |>
  filter(Age >= 80)

check_accuracy <- merged_exp |>
  filter(Cohort == 1876, Sex == "f")
```

```{r}
# final cleaning
final_data <- merged_exp |>
  filter(Cohort <= 1906, Cohort >= 1873) |>
  rename(Deaths = Cohort_Deaths)
```

Save data

```{r}
path = here("data")
write_csv(final_data, paste(path, "french_data.csv", sep="/"))
```
